name: Create Release
on:
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      release-tag:
        required: false
        description: "Release Tag"
      release-name:
        required: false
        description: "Release Name:"
      release-description:
        required: false
        description: "Release Description"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        
        id: create_release
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/releases \
          -f tag_name='${{ inputs.release-tag }}' \
          -f target_commitish='main' \
          -f name='${{ inputs.release-name }}' \
          -f body=${{ inputs.description-name }} \
          -F draft=false \
          -F prerelease=false \
          -F generate_release_notes=false 

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
