name: Deploy

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    permissions: write-all
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Get latest release tag
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/releases/latest > temp.json
          
          LATEST_RELEASE_TAG=$(jq '.tag_name' temp.json)
          echo "Tag name: "
          echo '${LATEST_RELEASE_TAG}'
          
          
#      - name: Deploy to server
#        run: |
#          gh api \
#          --method POST \
#          -H "Accept: application/vnd.github+json" \
#          /repos/FilipTelia/rel-dep-test/deployments \
#          -f ref='latest' \
#          -f payload='{ "deploy": "migrate" }' \
#          -f description='Deploy request from hubot' \
#          -f environment='prod'
          
#          echo "prod deployed"
    env:
      GH_TOKEN: ${{ github.token }}
        
