name: Deploy

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    permissions: write-all
    runs-on: ubuntu-latest
#    environment: prod
    steps:
      - name: Get latest release tag
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/releases/latest > temp.json
          
          LATEST_RELEASE_TAG=$(jq '.tag_name' temp.json | tr -d '"')
          echo "Tag name: "
          echo $LATEST_RELEASE_TAG
          echo "LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_TAG)" >> $GITHUB_ENV
          
          
      - name: Deploy to server
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments \
          -f ref='${{ env.LATEST_RELEASE_TAG }}' \
          -f description='DESCRIPTION: DEPLOYMENT OF LATEST RELEASE ${{ env.LATEST_RELEASE_TAG }}' \
          -f environment='prod' \
          -F auto_merge=false
          
          echo "prod deployed"
    env:
      GH_TOKEN: ${{ github.token }}
        
