name: Deploy

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deployment-prod:
    permissions: write-all
    runs-on: ubuntu-latest
#    environment: prod
    steps:
      - name: Get latest release tag
# Gets the tag of the latest created release and saves it as an environment variable
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/releases/latest > temp.json
          
          LATEST_RELEASE_TAG=$(jq '.tag_name' temp.json | tr -d '"')
          echo "Tag Name: "
          echo $LATEST_RELEASE_TAG
          echo "LATEST_RELEASE_TAG=$(echo $LATEST_RELEASE_TAG)" >> $GITHUB_ENV
          
          
      - name: Create Deployment
# Creates a new deployment with the latest release tag as reference
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments \
          -f ref='${{ env.LATEST_RELEASE_TAG }}' \
          -f description='DEPLOYMENT OF LATEST RELEASE: ${{ env.LATEST_RELEASE_TAG }}' \
          -f environment='${{ inputs.environment }}' \
          -f payload='****DEPLOYED**BY**${{ GITHUB.ACTOR }}' \
          -F auto_merge=false
          
          echo "Deployment created"
          
      - name: Get deployment id
# Gets the deployment ID to update the status in the next step
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments?ref=${{ env.LATEST_RELEASE_TAG }} > temp.json
          
          DEPLOYMENT_ID=$(jq '.[0].id' temp.json)
          echo "Deployment ID: "
          echo $DEPLOYMENT_ID
          echo "DEPLOYMENT_ID=$(echo $DEPLOYMENT_ID)" >> $GITHUB_ENV
          
      - name: Change status to in_progress
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
          -f environment='${{ inputs.environment }}' \
          -f state='in_progress' \
          -f log_url='https://github.com/FilipTelia/rel-dep-test/actions/runs/${{ GITHUB.RUN_ID }}' \
          -f environment_url='https://example.com/deployment/${{ env.DEPLOYMENT_ID }}/output'
      
      - name: Deploy to remote server
# This is where the actual deployment stuff can be done
        id: deployment
        run: |
          echo "Doing deployment stuff"
          sleep 10s
          echo "1"
          sleep 10s
          echo "2"
          sleep 10s
          echo "3"
          echo "Deployment finished"
          
      - name: Update status
# Updates the state of the deployment to success which will automatically change the status of the deployment from pending to active
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
          -f environment='${{ inputs.environment }}' \
          -f state='success' \
          -f log_url='https://github.com/FilipTelia/rel-dep-test/actions/runs/${{ GITHUB.RUN_ID }}' \
          -f environment_url='https://example.com/deployment/${{ env.DEPLOYMENT_ID }}/output' \
          -f description='Deployed by ${{ GITHUB.ACTOR }}' \
          -F auto_inactive=true
                
    env:
# The token that is needed for every step that uses the Github API
      GH_TOKEN: ${{ github.token }}
        
