name: Test

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo "prod deployed"
