name: Deploy

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to server
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/FilipTelia/rel-dep-test/deployments \
          -f ref='topic-branch' \
          -f payload='{ "deploy": "migrate" }' \
          -f description='Deploy request from hubot' 
          
          echo "prod deployed"
        
