name: Deploy

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to server
        run: echo "prod deployed"

  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to server
        run: echo "dev deployed"
        
  deployment-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy to server
        run: echo "test deployed"
