name: Workflow

# concurrency: prod

on:
#  push:
#    branches:
#      - main
      
  workflow_dispatch:

jobs:
  deployment-prod:
    runs-on: ubuntu-latest
#    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        run: echo "prod deployed"
